export interface NicheConfig {
  slug: string;
  name: string;
  plural: string;
  emoji: string;
  color: string;
  gradientFrom: string;
  gradientTo: string;
  title: string;
  metaDesc: string;
  h1: string;
  subheading: string;
  placeholder: string;
  keywords: string[];
  mustHaves: string[];
  industry: string;
  faqs: { q: string; a: string }[];
  stats: { label: string; value: string }[];
}

export const NICHES: NicheConfig[] = [
  {
    slug: "restaurants",
    name: "Restaurant",
    plural: "Restaurants",
    emoji: "🍽️",
    color: "#DC2626",
    gradientFrom: "#DC2626",
    gradientTo: "#EA580C",
    title: "Free Restaurant Website Grader — Check Your Restaurant Website Score | DevStudio",
    metaDesc: "Free AI website grader for restaurants. Check your restaurant website's score for online ordering, menu display, mobile experience, Google rankings, and table booking. Instant, free, no sign-up.",
    h1: "Free Restaurant Website Grader",
    subheading: "Is your restaurant website winning or losing customers? Our AI checks online ordering, menu display, mobile UX, Google Maps presence, booking system, and more — free, instant.",
    placeholder: "e.g. mario-pizza.com",
    keywords: ["restaurant website grader", "restaurant website checker", "restaurant website score", "restaurant website analysis"],
    mustHaves: ["Online Ordering / Menu", "Table Booking System", "Google Maps Embed", "Mobile-Friendly", "Food Photos", "Opening Hours Visible", "WhatsApp / Click-to-Call", "Customer Reviews"],
    industry: "Restaurant",
    faqs: [
      { q: "Why do restaurants need a good website?", a: "70% of diners check a restaurant's website before visiting. A poor website — slow, hard to read the menu, no booking button — sends customers to competitors. A great website drives reservations, orders, and foot traffic 24/7." },
      { q: "What should every restaurant website have?", a: "The essentials: a mobile-friendly design, fast-loading food photos, an easy-to-read menu, a prominent booking button (or OpenTable/Resy integration), your address on Google Maps, opening hours, and customer reviews." },
      { q: "How does our grader check restaurant websites?", a: "Our AI analyzes your restaurant site across 8 dimensions: design, SEO, performance, mobile UX, conversion (booking/order CTAs), security, accessibility, and Google discoverability — then gives you a grade and a specific action plan." },
      { q: "Can I check a competitor restaurant's website?", a: "Yes — enter any restaurant URL to see their grade and find gaps you can exploit. Common weaknesses include missing online ordering, slow loading on mobile, and no schema markup for local SEO." },
    ],
    stats: [{ label: "of diners check website first", value: "70%" }, { label: "leave if menu hard to read on mobile", value: "61%" }, { label: "more revenue with online ordering", value: "2×" }],
  },
  {
    slug: "salons",
    name: "Hair Salon",
    plural: "Hair Salons & Barbershops",
    emoji: "✂️",
    color: "#DB2777",
    gradientFrom: "#DB2777",
    gradientTo: "#9333EA",
    title: "Free Hair Salon Website Grader — Check Your Salon Website Score | DevStudio",
    metaDesc: "Free AI website grader for hair salons and barbershops. Check online booking, portfolio display, pricing, mobile experience, and Google rankings. Instant, free, no sign-up.",
    h1: "Free Hair Salon & Barbershop Website Grader",
    subheading: "Is your salon website booking appointments or losing them? Our AI checks your booking system, portfolio, pricing, mobile UX, and local SEO — free, instant, no sign-up.",
    placeholder: "e.g. glamoursalon.com",
    keywords: ["hair salon website grader", "salon website checker", "barbershop website score", "salon website analysis"],
    mustHaves: ["Online Booking System", "Portfolio / Gallery", "Pricing List", "Stylist Profiles", "Mobile-Friendly", "Google Maps / Location", "Before & After Photos", "Reviews / Testimonials"],
    industry: "Hair Salon",
    faqs: [
      { q: "Why is a good website critical for salons?", a: "Over 80% of people search online before booking a hair appointment. If your website doesn't show your work, prices, and an easy booking button, you're losing those customers to salons that do." },
      { q: "What should a salon website include?", a: "Must-haves: a photo gallery of your work, a clearly visible online booking button, a price list, stylist profiles, your location with Google Maps, customer reviews, and a mobile-friendly design." },
      { q: "How do I get more salon bookings from my website?", a: "Add an online booking system (Booksy, Vagaro, or a custom solution), put your phone number as click-to-call on mobile, show prices prominently, add before-and-after photos, and collect Google reviews." },
    ],
    stats: [{ label: "of salon bookings now happen online", value: "60%" }, { label: "more likely to book with online scheduling", value: "3×" }, { label: "abandon a website that's not mobile-friendly", value: "57%" }],
  },
  {
    slug: "dentists",
    name: "Dental Practice",
    plural: "Dental Practices & Dentists",
    emoji: "🦷",
    color: "#2563EB",
    gradientFrom: "#2563EB",
    gradientTo: "#0891B2",
    title: "Free Dentist Website Grader — Check Your Dental Practice Website Score | DevStudio",
    metaDesc: "Free AI website grader for dentists and dental practices. Check appointment booking, service pages, trust signals, local SEO, and patient conversion. Free, instant, no sign-up.",
    h1: "Free Dental Practice Website Grader",
    subheading: "Is your dental website attracting new patients or turning them away? Our AI checks appointment booking, service pages, trust signals, before/after photos, and local SEO — free, instant.",
    placeholder: "e.g. brightsmilesdental.com",
    keywords: ["dentist website grader", "dental practice website checker", "dental website score", "dentist website analysis"],
    mustHaves: ["Online Appointment Booking", "Service Pages (Implants, Whitening, etc.)", "Patient Reviews / Testimonials", "Before & After Gallery", "Insurance Info", "Doctor Bios", "Local SEO / Google Maps", "Emergency Contact"],
    industry: "Dental Practice",
    faqs: [
      { q: "Why do dental practices need a professional website?", a: "Patients choose a dentist largely based on their online presence. A trustworthy website with doctor bios, patient reviews, and easy appointment booking can be the difference between a full schedule and empty chairs." },
      { q: "What should a dentist website include?", a: "Must-haves: online appointment booking, service pages for each treatment, patient testimonials, before/after photos, insurance information, doctor credentials and headshots, and a clear emergency contact number." },
      { q: "How does local SEO affect dental practices?", a: "Most patients search 'dentist near me' — if you don't appear in Google's local 3-pack, you're invisible to those patients. Good local SEO (Google Business profile, local keywords, reviews) is the #1 driver of new dental patients." },
    ],
    stats: [{ label: "of patients research dentists online", value: "77%" }, { label: "more likely to book after seeing reviews", value: "4×" }, { label: "of dental searches happen on mobile", value: "65%" }],
  },
  {
    slug: "real-estate",
    name: "Real Estate Agent",
    plural: "Real Estate Agents & Agencies",
    emoji: "🏠",
    color: "#16A34A",
    gradientFrom: "#16A34A",
    gradientTo: "#0D9488",
    title: "Free Real Estate Website Grader — Check Your Realtor Website Score | DevStudio",
    metaDesc: "Free AI website grader for real estate agents and agencies. Check property listings, lead capture, mobile experience, IDX integration, and local SEO rankings. Free, instant, no sign-up.",
    h1: "Free Real Estate Agent Website Grader",
    subheading: "Is your real estate website generating buyer leads or losing them? Our AI checks property listings, lead forms, IDX integration, mobile UX, and local SEO — free and instant.",
    placeholder: "e.g. johndoerealestate.com",
    keywords: ["real estate website grader", "realtor website checker", "real estate agent website score", "realtor website analysis"],
    mustHaves: ["IDX Property Search", "Lead Capture Forms", "Featured Listings", "Agent Bio & Credentials", "Market Reports / Blog", "Mobile-Friendly", "Neighborhood Pages", "Client Testimonials"],
    industry: "Real Estate",
    faqs: [
      { q: "Why do real estate agents need a great website?", a: "95% of buyers search online before contacting an agent. Without a professional website with property search, you're invisible to the largest buyer pool in history." },
      { q: "What should a real estate website have?", a: "Must-haves: IDX property search, lead capture forms, featured listings with professional photos, agent bio, client testimonials, neighborhood pages, and a mortgage calculator." },
      { q: "How can a website generate more buyer leads?", a: "Lead-generating real estate websites use: free valuation tools, neighborhood guides, email capture for new listings, live chat, and retargeting. Our grader checks which of these you're missing." },
    ],
    stats: [{ label: "of buyers start search online", value: "95%" }, { label: "of real estate searches on mobile", value: "72%" }, { label: "more leads with IDX integration", value: "5×" }],
  },
  {
    slug: "auto-repair",
    name: "Auto Repair Shop",
    plural: "Auto Repair Shops & Mechanics",
    emoji: "🔧",
    color: "#D97706",
    gradientFrom: "#D97706",
    gradientTo: "#DC2626",
    title: "Free Auto Repair Shop Website Grader — Check Your Mechanic Website Score | DevStudio",
    metaDesc: "Free AI website grader for auto repair shops and mechanics. Check online booking, service lists, local SEO, customer reviews, and mobile experience. Free, instant, no sign-up.",
    h1: "Free Auto Repair Shop Website Grader",
    subheading: "Is your auto repair website winning new customers or losing them to the shop down the road? Our AI checks booking, services, reviews, local SEO, and more — free and instant.",
    placeholder: "e.g. joesgarageatl.com",
    keywords: ["auto repair website grader", "mechanic shop website checker", "car repair website score", "auto shop website analysis"],
    mustHaves: ["Online Appointment Booking", "Services List with Prices", "Customer Reviews", "Click-to-Call Button", "Location & Directions", "Brand Certifications", "Vehicle Makes Serviced", "Mobile-Friendly"],
    industry: "Auto Repair",
    faqs: [
      { q: "Why do auto repair shops need a website?", a: "When a car breaks down, people search immediately for the nearest trusted mechanic. Without a website showing reviews, services, and a phone number, you're invisible at the exact moment someone needs you most." },
      { q: "What should a mechanic shop website include?", a: "Must-haves: a prominent click-to-call button, full service list with pricing, customer reviews, your certifications (ASE, AAA), a map and directions, and an online appointment request form." },
    ],
    stats: [{ label: "of auto repair searches local", value: "85%" }, { label: "call within 24 hours of finding a shop", value: "88%" }, { label: "of customers check reviews first", value: "79%" }],
  },
  {
    slug: "gyms",
    name: "Gym & Fitness Studio",
    plural: "Gyms & Fitness Studios",
    emoji: "💪",
    color: "#7C3AED",
    gradientFrom: "#7C3AED",
    gradientTo: "#DB2777",
    title: "Free Gym & Fitness Studio Website Grader — Check Your Gym Website Score | DevStudio",
    metaDesc: "Free AI website grader for gyms and fitness studios. Check membership sign-up, class schedules, trial offers, mobile experience, and local SEO. Free, instant, no sign-up.",
    h1: "Free Gym & Fitness Studio Website Grader",
    subheading: "Is your gym website converting visitors into members? Our AI checks sign-up flows, class schedules, trial offers, social proof, and local SEO — free and instant.",
    placeholder: "e.g. powerhousefitness.com",
    keywords: ["gym website grader", "fitness studio website checker", "gym website score", "fitness website analysis"],
    mustHaves: ["Online Membership Sign-Up", "Class Schedule / Timetable", "Free Trial CTA", "Pricing / Membership Plans", "Trainer Profiles", "Before & After / Transformations", "Virtual Tour / Photos", "Mobile App Link"],
    industry: "Gym / Fitness Studio",
    faqs: [
      { q: "Why does a gym website matter for membership growth?", a: "Most gym searches happen in January (New Year) and summer (beach season). If your website doesn't have a clear free trial offer and easy sign-up, you lose those high-intent visitors to better-marketed competitors." },
      { q: "What should a gym website include?", a: "Must-haves: membership pricing, class timetables, a free trial or day pass offer, transformation photos, trainer profiles, virtual tour photos, and a mobile-friendly design since most searches happen on phones." },
    ],
    stats: [{ label: "of gym searches happen on mobile", value: "67%" }, { label: "more memberships with a free trial offer", value: "3×" }, { label: "of people research gyms online before visiting", value: "82%" }],
  },
  {
    slug: "law-firms",
    name: "Law Firm",
    plural: "Law Firms & Attorneys",
    emoji: "⚖️",
    color: "#1D4ED8",
    gradientFrom: "#1D4ED8",
    gradientTo: "#4338CA",
    title: "Free Law Firm Website Grader — Check Your Lawyer Website Score | DevStudio",
    metaDesc: "Free AI website grader for law firms and attorneys. Check practice area pages, attorney bios, case results, contact forms, and local SEO rankings. Free, instant, no sign-up.",
    h1: "Free Law Firm Website Grader",
    subheading: "Is your law firm website converting potential clients into consultations? Our AI checks practice areas, attorney credentials, case results, contact forms, and local SEO — free and instant.",
    placeholder: "e.g. smithlawgroup.com",
    keywords: ["law firm website grader", "attorney website checker", "lawyer website score", "law firm website analysis"],
    mustHaves: ["Practice Area Pages", "Attorney Bio & Credentials", "Case Results / Wins", "Free Consultation CTA", "Client Testimonials", "Awards & Bar Memberships", "Legal Blog / Resources", "Mobile-Friendly"],
    industry: "Law Firm",
    faqs: [
      { q: "Why do law firms need a strong website?", a: "96% of people seeking legal advice use a search engine first. Your website is your 24/7 pitch. Without strong attorney bios, case results, and a clear 'Free Consultation' CTA, you lose cases to competitors." },
      { q: "What should a law firm website include?", a: "Must-haves: dedicated practice area pages, detailed attorney profiles with credentials, testimonials, notable case results (without violating bar rules), a free consultation form, and your bar memberships/awards." },
    ],
    stats: [{ label: "of legal searches start online", value: "96%" }, { label: "more leads with a free consultation offer", value: "4×" }, { label: "of clients check reviews before hiring", value: "88%" }],
  },
  {
    slug: "plumbers",
    name: "Plumbing Business",
    plural: "Plumbers & Plumbing Services",
    emoji: "🚿",
    color: "#0891B2",
    gradientFrom: "#0891B2",
    gradientTo: "#2563EB",
    title: "Free Plumber Website Grader — Check Your Plumbing Business Website Score | DevStudio",
    metaDesc: "Free AI website grader for plumbers and plumbing companies. Check emergency contact, service areas, pricing, reviews, and local SEO. Free, instant, no sign-up.",
    h1: "Free Plumber & Plumbing Business Website Grader",
    subheading: "When a pipe bursts at 2am, people need a plumber NOW. Is your website ready to capture those emergency calls? Our AI checks your site instantly — free, no sign-up.",
    placeholder: "e.g. fastflowplumbing.com",
    keywords: ["plumber website grader", "plumbing company website checker", "plumbing website score", "plumber website analysis"],
    mustHaves: ["24/7 Emergency Number (Prominent)", "Click-to-Call Button", "Service Areas Listed", "Services with Pricing", "Customer Reviews", "Licensed & Insured Badge", "Same-Day Service CTA", "Mobile-Friendly"],
    industry: "Plumbing",
    faqs: [
      { q: "Why is a website critical for plumbers?", a: "Plumbing is an emergency service — people search 'plumber near me' when there's water pouring. If your phone number isn't front-and-center on mobile, they'll call the next plumber in the search results." },
      { q: "What should a plumber's website include?", a: "Must-haves: your phone number as click-to-call at the top of every page, '24/7 Emergency' badge, list of service areas, all services offered with pricing guides, license number, and customer reviews for trust." },
    ],
    stats: [{ label: "of plumbing searches are emergency calls", value: "68%" }, { label: "call the first result they find", value: "75%" }, { label: "of plumbing searches happen on mobile", value: "78%" }],
  },
  {
    slug: "electricians",
    name: "Electrical Business",
    plural: "Electricians & Electrical Contractors",
    emoji: "⚡",
    color: "#CA8A04",
    gradientFrom: "#CA8A04",
    gradientTo: "#D97706",
    title: "Free Electrician Website Grader — Check Your Electrical Business Website Score | DevStudio",
    metaDesc: "Free AI website grader for electricians and electrical contractors. Check emergency contact, service areas, licensing, reviews, and local SEO. Free, instant, no sign-up.",
    h1: "Free Electrician & Electrical Contractor Website Grader",
    subheading: "Is your electrical business website capturing leads from urgent calls and planned projects? Our AI audits your site in seconds — free, no sign-up required.",
    placeholder: "e.g. brightsparkelectrical.com",
    keywords: ["electrician website grader", "electrical contractor website checker", "electrician website score", "electrical company website analysis"],
    mustHaves: ["Emergency Contact Number", "Service Areas", "Residential & Commercial Services", "License & Insurance Info", "Customer Reviews", "Quote Request Form", "Safety Certifications", "Mobile-Friendly"],
    industry: "Electrical Contractor",
    faqs: [
      { q: "Why do electricians need a professional website?", a: "Most electrical work comes from homeowners searching locally. Without a website showing your license, reviews, and services, customers choose a competitor they can find and trust online." },
      { q: "What trust signals do electricians need on their website?", a: "The most important trust signals: your license number, insurance certificate, safety certifications, years of experience, customer reviews, and photos of completed projects." },
    ],
    stats: [{ label: "of homeowners search online for electricians", value: "85%" }, { label: "check license/credentials before calling", value: "71%" }, { label: "more likely to call with visible phone number", value: "2.5×" }],
  },
  {
    slug: "cleaning-services",
    name: "Cleaning Service",
    plural: "Cleaning Services & Maid Companies",
    emoji: "🧹",
    color: "#059669",
    gradientFrom: "#059669",
    gradientTo: "#0D9488",
    title: "Free Cleaning Service Website Grader — Check Your Cleaning Business Website Score | DevStudio",
    metaDesc: "Free AI website grader for cleaning services and maid companies. Check online booking, pricing, trust signals, service areas, and local SEO. Free, instant, no sign-up.",
    h1: "Free Cleaning Service Website Grader",
    subheading: "Is your cleaning business website booking recurring clients on autopilot? Our AI checks your booking flow, pricing, trust signals, and local SEO — free and instant.",
    placeholder: "e.g. sparklescleaningco.com",
    keywords: ["cleaning service website grader", "cleaning company website checker", "maid service website score", "cleaning business website analysis"],
    mustHaves: ["Online Booking / Quote Form", "Service Types (Deep Clean, Regular, Move-in/out)", "Pricing / Packages", "Background Check Badge", "Before & After Photos", "Customer Reviews", "Service Areas", "Recurring Service CTA"],
    industry: "Cleaning Service",
    faqs: [
      { q: "What makes a great cleaning service website?", a: "Customers want to trust who's coming into their home. Show background check status, insurance, team photos, and reviews prominently. Then make it effortless to book — ideally in under 60 seconds with instant price quotes." },
      { q: "How do cleaning companies get recurring clients online?", a: "The best cleaning websites offer a recurring discount (e.g., 10% off when you book weekly), show the savings vs one-time cleaning, and make it easy to set up automatic scheduled cleans." },
    ],
    stats: [{ label: "of cleaning clients book through websites", value: "65%" }, { label: "of bookings are recurring service (highest LTV)", value: "45%" }, { label: "more likely to book with instant pricing", value: "3×" }],
  },
  {
    slug: "hotels",
    name: "Hotel & B&B",
    plural: "Hotels, B&Bs & Accommodations",
    emoji: "🏨",
    color: "#7C3AED",
    gradientFrom: "#4F46E5",
    gradientTo: "#7C3AED",
    title: "Free Hotel Website Grader — Check Your Hotel & B&B Website Score | DevStudio",
    metaDesc: "Free AI website grader for hotels, B&Bs, and vacation rentals. Check direct booking engine, room photos, local attractions, reviews, and SEO. Free, instant, no sign-up.",
    h1: "Free Hotel & B&B Website Grader",
    subheading: "Is your hotel website driving direct bookings or sending guests to Booking.com (who take 15–25% commission)? Our AI audit shows you exactly what to fix — free, instant.",
    placeholder: "e.g. seasideinnhotel.com",
    keywords: ["hotel website grader", "hotel website checker", "B&B website score", "hotel website analysis"],
    mustHaves: ["Direct Booking Engine", "High-Quality Room Photos", "Virtual Tour", "Local Attractions Guide", "Reviews (TripAdvisor/Google)", "Amenities List", "Best Rate Guarantee", "Mobile-Friendly"],
    industry: "Hotel",
    faqs: [
      { q: "Why should hotels focus on their own website?", a: "Every booking through Booking.com or Expedia costs you 15-25% commission. A great direct booking website with a 'Best Rate Guarantee' keeps that commission in your pocket. Even converting 20% of OTA bookings to direct saves thousands per year." },
      { q: "What should a hotel website include?", a: "Must-haves: a fast direct booking engine, professional photography of all room types, a local guide/attractions page, guest reviews, clear amenity list, cancellation policy, and a mobile-first design." },
    ],
    stats: [{ label: "of travelers visit hotel website before booking", value: "83%" }, { label: "OTA commission saved with direct booking", value: "20%" }, { label: "of hotel searches happen on mobile", value: "70%" }],
  },
  {
    slug: "landscaping",
    name: "Landscaping Business",
    plural: "Landscaping & Lawn Care Companies",
    emoji: "🌿",
    color: "#15803D",
    gradientFrom: "#15803D",
    gradientTo: "#16A34A",
    title: "Free Landscaping Website Grader — Check Your Lawn Care Business Website Score | DevStudio",
    metaDesc: "Free AI website grader for landscaping and lawn care businesses. Check portfolio, quote forms, service areas, seasonal offers, and local SEO. Free, instant, no sign-up.",
    h1: "Free Landscaping & Lawn Care Website Grader",
    subheading: "Is your landscaping website turning website visitors into recurring lawn care clients? Our AI checks your portfolio, quote forms, seasonal offers, and local SEO — free and instant.",
    placeholder: "e.g. greenthumblandscaping.com",
    keywords: ["landscaping website grader", "lawn care website checker", "landscaping business website score", "lawn service website analysis"],
    mustHaves: ["Project Portfolio / Before & After", "Free Quote Request Form", "Services List (Mowing, Design, Hardscape)", "Seasonal Promotions", "Service Area Map", "Licensed & Insured Badge", "Customer Reviews", "Recurring Service Plans"],
    industry: "Landscaping",
    faqs: [
      { q: "What should a landscaping website show to win clients?", a: "Portfolio photos are everything in landscaping. Show dramatic before-and-afters, your equipment, and your team. Then make it easy to request a free quote — most landscaping clients decide based on the quality of past work." },
      { q: "How do lawn care companies build recurring revenue online?", a: "The best lawn care websites sell maintenance plans (weekly/monthly mowing, seasonal cleanup) with clear pricing and easy sign-up. Recurring clients are worth 5-10× more than one-time jobs." },
    ],
    stats: [{ label: "of homeowners research landscapers online", value: "78%" }, { label: "more valuable: recurring vs one-time clients", value: "8×" }, { label: "of quotes requested via website vs phone", value: "55%" }],
  },
  {
    slug: "pet-services",
    name: "Pet Service Business",
    plural: "Pet Groomers, Vets & Pet Services",
    emoji: "🐾",
    color: "#EA580C",
    gradientFrom: "#EA580C",
    gradientTo: "#DC2626",
    title: "Free Pet Business Website Grader — Check Your Veterinary or Pet Grooming Website Score | DevStudio",
    metaDesc: "Free AI website grader for vets, pet groomers, dog walkers, and pet businesses. Check booking, services, photos, trust signals, and local SEO. Free, instant, no sign-up.",
    h1: "Free Pet Services Website Grader",
    subheading: "Is your pet business website booking new clients and keeping regulars? Our AI checks your booking system, service photos, trust signals, and local SEO — free and instant.",
    placeholder: "e.g. happypawsgrooming.com",
    keywords: ["pet grooming website grader", "vet website checker", "dog walker website score", "pet business website analysis"],
    mustHaves: ["Online Booking / Appointment", "Service Packages & Pricing", "Pet Photos / Before & After Grooms", "Staff Credentials / Certifications", "Pet Health/Safety Policy", "Customer Reviews", "Service Areas", "Emergency Vet Contact (for vet sites)"],
    industry: "Pet Services",
    faqs: [
      { q: "Why do pet owners care so much about a business website?", a: "Pet owners treat their animals like family. They research extensively before trusting anyone with their pet. A website showing certifications, real pet photos, safety policies, and glowing reviews builds the trust needed to win a loyal, long-term client." },
      { q: "What converts pet owners into regular clients?", a: "The highest-converting pet service websites show: before/after grooming photos, clear pricing, online booking with instant confirmation, staff credentials, and a loyalty/membership program for regular clients." },
    ],
    stats: [{ label: "of pet owners search for services online", value: "82%" }, { label: "more likely to book with photos of pets", value: "2×" }, { label: "of pet clients become repeat customers", value: "70%" }],
  },
  {
    slug: "photographers",
    name: "Photography Business",
    plural: "Photographers & Photography Studios",
    emoji: "📷",
    color: "#6D28D9",
    gradientFrom: "#6D28D9",
    gradientTo: "#4F46E5",
    title: "Free Photographer Website Grader — Check Your Photography Business Website Score | DevStudio",
    metaDesc: "Free AI website grader for photographers and photography studios. Check portfolio, booking flow, pricing, SEO, and client experience. Free, instant, no sign-up.",
    h1: "Free Photographer Website Grader",
    subheading: "Is your photography website winning bookings or just getting compliments? Our AI checks your portfolio, pricing, booking flow, client galleries, and SEO — free and instant.",
    placeholder: "e.g. sarahjonesphotography.com",
    keywords: ["photographer website grader", "photography website checker", "photography business website score", "photographer website analysis"],
    mustHaves: ["Portfolio Gallery (by Category)", "Pricing / Investment Guide", "Booking / Inquiry Form", "About / Story Page", "Client Testimonials", "Blog / Styled Shoots", "Social Media Links (Instagram)", "Mobile Gallery Optimization"],
    industry: "Photography",
    faqs: [
      { q: "Why is SEO important for photographers?", a: "Photography is an extremely competitive market. 'Wedding photographer [city]' gets thousands of searches per month. Ranking on the first page for your location + niche is the highest-ROI thing a photographer can do." },
      { q: "What should a photographer's website include?", a: "Must-haves: categorized portfolio gallery (weddings, portraits, commercial), a clear pricing/investment page, an easy inquiry form, client testimonials, an About page showing your personality, and strong Instagram integration." },
    ],
    stats: [{ label: "of couples book their photographer online", value: "89%" }, { label: "of photographers are found via Google", value: "75%" }, { label: "more bookings with a pricing page", value: "2×" }],
  },
  {
    slug: "chiropractors",
    name: "Chiropractic Practice",
    plural: "Chiropractors & Physical Therapists",
    emoji: "🦴",
    color: "#0891B2",
    gradientFrom: "#0891B2",
    gradientTo: "#2563EB",
    title: "Free Chiropractor Website Grader — Check Your Chiropractic Practice Website Score | DevStudio",
    metaDesc: "Free AI website grader for chiropractors and physical therapists. Check new patient booking, conditions treated, insurance info, trust signals, and local SEO. Free, instant, no sign-up.",
    h1: "Free Chiropractor Website Grader",
    subheading: "Is your chiropractic website attracting new patients or turning them away? Our AI checks patient booking, conditions treated, insurance details, trust signals, and local SEO — free and instant.",
    placeholder: "e.g. backtohealth-chiro.com",
    keywords: ["chiropractor website grader", "chiropractic website checker", "physical therapist website score", "chiropractor website analysis"],
    mustHaves: ["New Patient Appointment Booking", "Conditions Treated Pages", "Insurance / Payment Info", "Doctor Credentials", "Patient Testimonials", "New Patient Special Offer", "Before & After / Success Stories", "Educational Blog / Videos"],
    industry: "Chiropractic Practice",
    faqs: [
      { q: "How do chiropractors attract new patients online?", a: "The best chiropractic websites offer a 'New Patient Special' (e.g., first visit $49) prominently on the homepage. This dramatically lowers the barrier to try a new chiropractor. Pair with strong Google reviews and a clear booking button." },
      { q: "What pages should a chiropractic website have?", a: "Must-haves: dedicated pages for each condition treated (back pain, neck pain, sciatica, sports injury), insurance information, doctor credentials and bio, patient success stories, and FAQs for common questions about chiropractic care." },
    ],
    stats: [{ label: "of patients research chiropractors online", value: "73%" }, { label: "more new patients with a new patient offer", value: "40%" }, { label: "of chiropractic searches are on mobile", value: "68%" }],
  },
  {
    slug: "accountants",
    name: "Accounting Firm",
    plural: "Accountants & Bookkeepers",
    emoji: "📊",
    color: "#1D4ED8",
    gradientFrom: "#1D4ED8",
    gradientTo: "#4338CA",
    title: "Free Accountant Website Grader — Check Your Accounting Firm Website Score | DevStudio",
    metaDesc: "Free AI website grader for accountants and bookkeepers. Check service pages, trust signals, tax deadline content, client portal, and SEO. Free, instant, no sign-up.",
    h1: "Free Accounting Firm Website Grader",
    subheading: "Is your accounting website winning new clients or blending into a sea of boring firm websites? Our AI checks your services, trust signals, lead generation, and SEO — free and instant.",
    placeholder: "e.g. precisionaccounting.com",
    keywords: ["accountant website grader", "accounting firm website checker", "bookkeeper website score", "CPA website analysis"],
    mustHaves: ["Service Pages (Tax, Audit, Bookkeeping)", "CPA Credentials / Bios", "Client Portal Link", "Consultation Request Form", "Industry Specializations", "Blog / Tax Tips", "Client Testimonials", "Pricing Tiers / Packages"],
    industry: "Accounting",
    faqs: [
      { q: "What makes an accounting website stand out?", a: "Most accounting websites look identical. Stand out by niching down — 'accountant for restaurants' or 'bookkeeper for e-commerce brands' — and build dedicated pages for each niche. This converts far better than generic pages." },
      { q: "What should an accounting firm website include?", a: "Must-haves: service pages for each offering, CPA credentials, a client portal link, pricing packages, industry specialization pages, a blog with tax tips (builds SEO), and a clear consultation booking button." },
    ],
    stats: [{ label: "of SMBs switch accountants based on website quality", value: "42%" }, { label: "more leads with niche-specific service pages", value: "3×" }, { label: "of accounting clients found via Google", value: "67%" }],
  },
  {
    slug: "insurance-agents",
    name: "Insurance Agency",
    plural: "Insurance Agents & Brokers",
    emoji: "🛡️",
    color: "#065F46",
    gradientFrom: "#065F46",
    gradientTo: "#0D9488",
    title: "Free Insurance Agency Website Grader — Check Your Insurance Website Score | DevStudio",
    metaDesc: "Free AI website grader for insurance agents and agencies. Check quote forms, product pages, trust signals, carrier logos, and local SEO. Free, instant, no sign-up.",
    h1: "Free Insurance Agency Website Grader",
    subheading: "Is your insurance website generating online quote requests or just existing online? Our AI checks your quote forms, product pages, trust signals, and local SEO — free and instant.",
    placeholder: "e.g. shieldinsurancegroup.com",
    keywords: ["insurance agent website grader", "insurance agency website checker", "insurance website score", "insurance broker website analysis"],
    mustHaves: ["Online Quote Request Form", "Coverage Types Pages", "Carrier Logos / Partners", "Licensed Agent Info", "Client Testimonials", "Blog / Coverage Guides", "Click-to-Call Button", "Claims Process Info"],
    industry: "Insurance Agency",
    faqs: [
      { q: "Why is a website critical for insurance agents?", a: "Insurance comparison shopping starts online. If your website doesn't offer instant quotes or clearly explain your coverage options, prospects go directly to aggregators like NerdWallet or competitors who make it easier." },
      { q: "What should an insurance agency website include?", a: "Must-haves: quick quote forms for each product (auto, home, life, business), carrier partner logos, license information, coverage explanation pages, client reviews, and a prominent phone number." },
    ],
    stats: [{ label: "of insurance buyers research online first", value: "87%" }, { label: "more leads with an online quote form", value: "4×" }, { label: "switch agents if website is unprofessional", value: "59%" }],
  },
  {
    slug: "bakeries",
    name: "Bakery & Café",
    plural: "Bakeries, Cake Shops & Cafés",
    emoji: "🧁",
    color: "#D97706",
    gradientFrom: "#D97706",
    gradientTo: "#EA580C",
    title: "Free Bakery Website Grader — Check Your Bakery & Cake Shop Website Score | DevStudio",
    metaDesc: "Free AI website grader for bakeries, cake shops, and cafés. Check online ordering, custom order forms, product photos, Instagram integration, and local SEO. Free, instant, no sign-up.",
    h1: "Free Bakery & Cake Shop Website Grader",
    subheading: "Is your bakery website making mouths water and driving pre-orders? Our AI checks your product photos, ordering flow, custom cake forms, and local SEO — free and instant.",
    placeholder: "e.g. sweetdreamsbakery.com",
    keywords: ["bakery website grader", "cake shop website checker", "bakery website score", "bakery website analysis"],
    mustHaves: ["Online Pre-Order / Shop", "Custom Order Request Form", "High-Quality Product Photos", "Allergen / Ingredient Info", "Menu with Pricing", "Instagram Gallery Feed", "Pickup / Delivery Options", "Wedding Cake Portfolio"],
    industry: "Bakery",
    faqs: [
      { q: "What makes a bakery website successful?", a: "Bakery sales are driven by emotion — beautiful photography. A website with drool-worthy photos, clear pricing, and a simple pre-order system will convert browsers into buyers. Instagram integration is critical since most bakery discovery happens there." },
      { q: "Should bakeries sell online?", a: "Yes — even a simple pre-order system for pickup can increase revenue 30-50%. Offering custom orders (cakes, event orders) online with a form and deposit payment reduces phone time and captures leads 24/7." },
    ],
    stats: [{ label: "of cake orders now start online", value: "58%" }, { label: "more revenue with online pre-orders", value: "35%" }, { label: "discover bakeries through Instagram/Google", value: "72%" }],
  },
  {
    slug: "nail-salons",
    name: "Nail Salon & Spa",
    plural: "Nail Salons & Day Spas",
    emoji: "💅",
    color: "#BE185D",
    gradientFrom: "#BE185D",
    gradientTo: "#9333EA",
    title: "Free Nail Salon Website Grader — Check Your Nail Salon & Spa Website Score | DevStudio",
    metaDesc: "Free AI website grader for nail salons and spas. Check online booking, service menus, nail art gallery, pricing, and local SEO. Free, instant, no sign-up.",
    h1: "Free Nail Salon & Day Spa Website Grader",
    subheading: "Is your nail salon website fully booked or struggling to fill appointments? Our AI checks your booking system, nail art gallery, pricing, and local SEO — free and instant.",
    placeholder: "e.g. prettynailsspa.com",
    keywords: ["nail salon website grader", "nail salon website checker", "spa website score", "nail salon website analysis"],
    mustHaves: ["Online Appointment Booking", "Service Menu with Pricing", "Nail Art Gallery", "Technician Profiles", "Loyalty / Rewards Program", "Gift Cards", "Sanitation / Safety Policy", "Instagram Portfolio"],
    industry: "Nail Salon",
    faqs: [
      { q: "How do nail salons get fully booked through their website?", a: "The top-performing nail salon websites make booking effortless — customers can see available slots and book in under 60 seconds. They also show a gallery of nail art styles to set expectations and attract clients who want specific looks." },
      { q: "What should a nail salon website include?", a: "Must-haves: online booking that shows real-time availability, a service menu with prices, nail art gallery (organized by style), technician profiles, gift card sales, sanitation policy, and a Google Reviews section." },
    ],
    stats: [{ label: "of salon clients book online vs calling", value: "67%" }, { label: "more revenue from clients who book online", value: "25%" }, { label: "of nail salon searches are 'near me'", value: "80%" }],
  },
  {
    slug: "contractors",
    name: "Construction & Contractor",
    plural: "Contractors & Construction Companies",
    emoji: "🏗️",
    color: "#92400E",
    gradientFrom: "#92400E",
    gradientTo: "#B45309",
    title: "Free Contractor Website Grader — Check Your Construction Company Website Score | DevStudio",
    metaDesc: "Free AI website grader for contractors and construction companies. Check project portfolio, quote forms, licensing, insurance, and local SEO. Free, instant, no sign-up.",
    h1: "Free Contractor & Construction Company Website Grader",
    subheading: "Is your contractor website winning bids or losing them to competitors with better websites? Our AI checks your portfolio, credentials, quote forms, and local SEO — free and instant.",
    placeholder: "e.g. eliteconstruction.com",
    keywords: ["contractor website grader", "construction company website checker", "contractor website score", "builder website analysis"],
    mustHaves: ["Project Portfolio with Photos", "License & Insurance Proof", "Free Quote Request Form", "Services List (Remodel, New Build, etc.)", "Customer Reviews / References", "Bonding Information", "Service Areas", "Project Timeline / Process"],
    industry: "Construction / Contracting",
    faqs: [
      { q: "Why do contractors need a professional website?", a: "Homeowners doing major renovations are making $10,000–$100,000+ decisions. They research extensively. A website showing your portfolio, license, insurance, and reviews builds the trust needed to win those big projects." },
      { q: "What trust signals matter most for contractors?", a: "The most important: a portfolio with real project photos (before/during/after), your license number and insurance certificate, references or Google Reviews, years in business, and any manufacturer certifications (GAF, CertainTeed, etc.)." },
    ],
    stats: [{ label: "of homeowners research contractors online", value: "91%" }, { label: "reject a contractor with no online presence", value: "64%" }, { label: "more leads with a project portfolio", value: "5×" }],
  },
];

export const NICHE_MAP = Object.fromEntries(NICHES.map(n => [n.slug, n]));
